# Generated by Django 6.0.7 on 2026-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('person_age', models.IntegerField()),
                ('person_income', models.FloatField()),
                ('person_emp_length', models.FloatField(null=True)),
                ('person_home_ownership', models.CharField(max_length=20)),
                ('loan_intent', models.CharField(max_length=30)),
                ('loan_grade', models.CharField(max_length=5)),
                ('loan_amnt', models.FloatField()),
                ('loan_int_rate', models.FloatField(null=True)),
                ('loan_percent_income', models.FloatField()),
                ('cb_person_default_on_file', models.CharField(max_length=5)),
                ('cb_person_cred_hist_length', models.IntegerField()),
                ('risk_score', models.FloatField(blank=True, default=None, null=True)),
                ('risk_tier', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
